# Generated by Django 3.2.3 on 2021-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'group'), name='unique enroll'),
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='accounts_enrollment',
        ),
    ]
