# Generated by Django 3.2.3 on 2021-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210614_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='N_sessions',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
