# Generated by Django 3.2.3 on 2021-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_group_n_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='N_sessions',
            field=models.IntegerField(null=True),
        ),
    ]
