# Generated by Django 3.2.3 on 2021-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_group_n_sessions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('group_name',), name='unique group'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='accounts_group',
        ),
    ]
